### ISSUE TITLE
Choose option recognize only two fingers

### ISSUE THREAD

**Issue by darhma** [ndleyton/OneTwo#13]
Xiaomi redmi note 7
Android pie

**Comment by ndleyton** [comment]
Hi, I'm sorry I was having some issues and had left personal projects behind.

Would you still like this feature to be implemented?

**Comment by darhma** [comment]
Hi, don't worry. I had uninstalled the app because I was using it to select the first player and switched to another non-opensource app. I just reinstalled and tried the app again (now I'm on android 10 with custom rom) and everything seems to work. For me you can close the issue, I don't know if it was an android version problem or what else. Thanks, I'm glad to be able to use your app again since it's open source and is on f-droid.
