### ISSUE TITLE
No longer builds to F-droid

### ISSUE THREAD

**Issue by KrisZane** [ndleyton/OneTwo#16]
Hey @ndleyton awesome little app, been using it for quite a while. I only recently noticed you are no longer building to F-Droid?

Is this something you will start doing again? Is it something I can help with?

**Comment by ndleyton** [comment]
HI!, thanks!
I will, it was a matter of compatibility fir newer builds of Android, so I'm updating the App for that

**Comment by KrisZane** [comment]
@ndleyton Awesome, thanks man! :P

**Comment by cweiske** [comment]
The [f-droid OneTwo metadata file](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.nicue.onetwo.yml) ([added 2017-05](https://gitlab.com/fdroid/rfp/-/issues/150)) says the f-droid [should not build](https://f-droid.org/en/docs/Build_Metadata_Reference/#AutoUpdateMode) the `.apk` itself:

    AutoUpdateMode: None

Is there a reason for that? Can that be changed so f-droid builds the packages automatically on its own whenever a new version is tagged?

**Comment by cweiske** [comment]
Today version 1.1.7  appeared on f-droid.

It was a manual version bump: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9201

**Comment by KrisZane** [comment]
Awesome! :P
